import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	team,
	analytics,
}: {
	children: React.ReactNode;
	team: React.ReactNode;
	analytics: React.ReactNode;
}) {
	return (
		<html lang='en' className='dark'>
			<body className={inter.className}>
				<Navbar />
				<main className='container mx-auto mt-10'>
					<div className='grid grid-cols-1 md:grid-cols-2 gap-5'>
						{team}
						{analytics}
					</div>
					{children}
				</main>
			</body>
		</html>
	);
}
